from request import Request
from scrape import Scrape


requestToTopPage = Request("https://finance.yahoo.co.jp")
textInTopPage = requestToTopPage.send()
scrapeInTopPage = Scrape(textInTopPage)

[firstStockUrl] = scrapeInTopPage.getUrl("#stockrank > div > div > section:nth-child(1) > ol > li:nth-child(1) > a")
requestToFirstPage = Request(firstStockUrl)
textInFirstPage = requestToFirstPage.send()
scrapeInFirstPage = Scrape(textInFirstPage)
[firstStockNumber]= scrapeInFirstPage.getStockInfo("#industry > span")
[firstStockName] = scrapeInFirstPage.getStockInfo("#root > main > div > div > div.XuqDlHPN > div:nth-child(3) > section._1zZriTjI._2l2sDX5w > div._1nb3c4wQ > header > div.DL5lxuTC > h1")
print(firstStockName)
print(firstStockNumber)

[secondStockUrl] = scrapeInTopPage.getUrl("#stockrank > div > div > section:nth-child(1) > ol > li:nth-child(2) > a")
requestToSecondPage = Request(secondStockUrl)
textInSecondPage = requestToSecondPage.send()
scrapeInSecondPage = Scrape(textInSecondPage)
[secondStockNumber]= scrapeInSecondPage.getStockInfo("#industry > span")
[secondStockName] = scrapeInSecondPage.getStockInfo("#root > main > div > div > div.XuqDlHPN > div:nth-child(3) > section._1zZriTjI._2l2sDX5w > div._1nb3c4wQ > header > div.DL5lxuTC > h1")
print(secondStockName)
print(secondStockNumber)

[thirdStockUrl] = scrapeInTopPage.getUrl("#stockrank > div > div > section:nth-child(1) > ol > li:nth-child(3) > a")
requestToThirdPage = Request(thirdStockUrl)
textInThirdPage = requestToThirdPage.send()
scrapeInThirdPage = Scrape(textInThirdPage)
[thirdStockNumber]= scrapeInThirdPage.getStockInfo("#industry > span")
[thirdStockName] = scrapeInThirdPage.getStockInfo("#root > main > div > div > div.XuqDlHPN > div:nth-child(3) > section._1zZriTjI._2l2sDX5w > div._1nb3c4wQ > header > div.DL5lxuTC > h1")
print(thirdStockName)
print(thirdStockNumber)

[fourthStockUrl] = scrapeInTopPage.getUrl("#stockrank > div > div > section:nth-child(1) > ol > li:nth-child(4) > a")
requestToFourthPage = Request(fourthStockUrl)
textInFourthPage = requestToFourthPage.send()
scrapeInFourthPage = Scrape(textInFourthPage)
[fourthStockNumber]= scrapeInFourthPage.getStockInfo("#industry > span")
[fourthStockName] = scrapeInFourthPage.getStockInfo("#root > main > div > div > div.XuqDlHPN > div:nth-child(3) > section._1zZriTjI._2l2sDX5w > div._1nb3c4wQ > header > div.DL5lxuTC > h1")
print(fourthStockName)
print(fourthStockNumber)

[fifthStockUrl] = scrapeInTopPage.getUrl("#stockrank > div > div > section:nth-child(1) > ol > li:nth-child(5) > a")
requestToFifthPage = Request(fifthStockUrl)
textInFifthPage = requestToFifthPage.send()
scrapeInFifthPage = Scrape(textInFifthPage)
[fifthStockNumber]= scrapeInFifthPage.getStockInfo("#industry > span")
[fifthStockName] = scrapeInFifthPage.getStockInfo("#root > main > div > div > div.XuqDlHPN > div:nth-child(3) > section._1zZriTjI._2l2sDX5w > div._1nb3c4wQ > header > div.DL5lxuTC > h1")
print(fifthStockName)
print(fifthStockNumber)
